server:
  port: 60000

spring:
#  config:
#    import: optional:configserver:http://127.0.0.1:8888/
#  cloud:
#    config:
##      name: ecommerce
#      name: user-service
  application:
    name: user-service
#  zipkin:
#    base-url: http://13.124.192.188:9411
#    enabled: true
#  sleuth:
#    sampler:
#      probability: 1.0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 5
  datasource:
    url: jdbc:mysql://localhost:3306/study?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  #    prefer-ip-address: true
#  #    ip-address: ${server.address}
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true

greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    com.example.userservice.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh
#        , info, metrics, prometheus

#gateway:
#  ip: 10.204.136.204

#token:
#  expiration_time: 86400000
#  secret: user_token
#
