server:
  port: 8888


spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 5
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kmkwk/Config-Server.git
          default-label: main
          search-paths: properties

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh